import Card from "@mui/material/Card";
import Container from "@mui/material/Container";
import Paper from "@mui/material/Paper";
import Typography from "@mui/material/Typography";
import Divider from "@mui/material/Divider";
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from "next";

import Head from "next/head";
import { useContext } from "react";

import HeaderBar from "../components/header/headerBar";
import IndexParticle from "../components/indexParticle";
import { DarkModeContext } from "../components/muiThemeProvider";
import RecentPosts from "../components/recentPosts";
import scanFiles from "../lib/scanMdxFiles";

export default function Home({ LatestPosts }) {
  const darkMode = useContext(DarkModeContext);
  return (
    <>
      <Head>
        <title>CharlieZhuoBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <nav>
        <HeaderBar></HeaderBar>
      </nav>

      <main>
        {darkMode.inDarkModeContext ? <IndexParticle></IndexParticle> : <></>}
        <Container maxWidth="md" sx={{ paddingBlockStart: "20vh" }}>
          <Paper sx={{ padding: "1rem" }} elevation={0}>
            <Typography variant="h2">Hi. Welcome to my blog.</Typography>
            <Typography variant="h4">
              I&apos;m Charlie,a front-end developer.
            </Typography>
            <Typography variant="h4">
              I talk about React,Next.js,styling and my develop experience.
            </Typography>
          </Paper>
          <Divider sx={{ marginTop: "30vh" }}></Divider>

          <Paper elevation={0}>
            <RecentPosts posts={LatestPosts}></RecentPosts>
          </Paper>
        </Container>
      </main>

      <footer></footer>
    </>
  );
}
export const getStaticProps: GetStaticProps = async () => {
  const LatestPosts = await scanFiles();
  return {
    props: { LatestPosts },
  };
};
